### ISSUE TITLE
Make dt better

### ISSUE THREAD

**Issue by deok420** [RXVAN/1337.club#4]
make it better or i leak source :O

**Comment by many1337** [comment]
lmao u are a god, u LEAK PUBLIC SOURCEXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDd

**Comment by abornite** [comment]
shut up idiot 
🧐

**Comment by deok420** [comment]
> 
> 
> lmao u are a god, u LEAK PUBLIC SOURCEXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDd

thats the joke

**Comment by deok420** [comment]
> 
> 
> shut up idiot
> 🧐

no u

**Comment by RXVAN** [comment]
you weird ass bums shut up ffs

**Comment by deok420** [comment]
> 
> 
> you weird ass bums shut up ffs

pls men im trying to meik media withg chit

**Comment by SadKwitty** [comment]
deok being dumb, this cheat so P it miss baim and dt dont work, whats the issue??

**Comment by deok420** [comment]
> deok being dumb, this cheat so P it miss baim and dt dont work, whats the issue??

Yes omg cheat is bester, deok is just retardo

**Comment by SadKwitty** [comment]
Cheat Perfect. User Issue. Thread Closed. Banned for Undermining.

**Comment by Bleszu** [comment]
Make dt better kid
